### ISSUE TITLE
catalog app crash in markdown.js

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/skeleton-bridge#17]
Here is the stack trace:

```
ERROR [app-router] Error: Error invoking AuMarkdown. Check the inner error for details.
------------------------------------------------
inner error: ReferenceError: showdown is not defined
    at new AuMarkdown (http://localhost:3000/src/shared/markdown.js!transpiled:40:32)
    at Object.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:344:14)
    at InvocationHandler.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
    at Container.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
    at ProviderResolver.get (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1459:74)
    at Container.get (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:494:23)
    at Container.elementContainerGet [as get] (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1508:17)
    at HtmlBehaviorResource.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:3353:58)
    at applyInstructions (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1586:33)
    at ViewFactory.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1810:9)
    at new AuMarkdown (http://localhost:3000/src/shared/markdown.js!transpiled:40:32)
    at Object.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:344:14)
    at InvocationHandler.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
    at Container.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
    at ProviderResolver.get (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1459:74)
    at Container.get (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:494:23)
    at Container.elementContainerGet [as get] (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1508:17)
    at HtmlBehaviorResource.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:3353:58)
    at applyInstructions (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1586:33)
    at ViewFactory.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1810:9)
    at new AggregateError (http://localhost:3000/jspm_packages/npm/aurelia-pal@1.0.0-beta.1.0.1/aurelia-pal.js:20:13)
    at Container.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:559:15)
    at ProviderResolver.get (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1459:74)
    at Container.get (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:494:23)
    at Container.elementContainerGet [as get] (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1508:17)
    at HtmlBehaviorResource.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:3353:58)
    at applyInstructions (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1586:33)
    at ViewFactory.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1810:9)
    at HtmlBehaviorResource.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:3374:62)
    at applyInstructions (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1586:33)
```

I discovered it at almost midnight (meaning that I am not in a mood to find out what the problem is :-) ) when tried to use the clone of the skeleton bridge as the beginning of a "research project". This crash took place on unmodified clone.

**Comment by adriatic** [comment]
I just could not leave this alone - so I looked in the [markdown.js](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/src/shared/markdown.js#L2) and replaced this line #2 with 

```
import showdown from 'showdown';
```

Running the app again resulted with next crash (note that fixing the above referenced import statement) moved the execution a bit further

```
inner error: Error: Extension "prettify" could not be loaded. It was either not found or is not a valid extension.
    at Error (native)
    at _parseExtension (http://localhost:3000/jspm_packages/github/showdownjs/showdown@1.3.0/dist/showdown.js:705:15)
    at Array.forEach (native)
    at Object.forEach (http://localhost:3000/jspm_packages/github/showdownjs/showdown@1.3.0/dist/showdown.js:443:9)
    at _constructor (http://localhost:3000/jspm_packages/github/showdownjs/showdown@1.3.0/dist/showdown.js:675:23)
    at new showdown.Converter (http://localhost:3000/jspm_packages/github/showdownjs/showdown@1.3.0/dist/showdown.js:647:3)
    at new AuMarkdown (http://localhost:3000/src/shared/markdown.js!transpiled:42:28)
    at Object.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:344:14)
    at InvocationHandler.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
    at Container.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
    at Error (native)
    at _parseExtension (http://localhost:3000/jspm_packages/github/showdownjs/showdown@1.3.0/dist/showdown.js:705:15)
    at Array.forEach (native)
    at Object.forEach (http://localhost:3000/jspm_packages/github/showdownjs/showdown@1.3.0/dist/showdown.js:443:9)
    at _constructor (http://localhost:3000/jspm_packages/github/showdownjs/showdown@1.3.0/dist/showdown.js:675:23)
    at new showdown.Converter (http://localhost:3000/jspm_packages/github/showdownjs/showdown@1.3.0/dist/showdown.js:647:3)
    at new AuMarkdown (http://localhost:3000/src/shared/markdown.js!transpiled:42:28)
    at Object.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:344:14)
    at InvocationHandler.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
    at Container.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
    at new AggregateError (http://localhost:3000/jspm_packages/npm/aurelia-pal@1.0.0-beta.1.0.1/aurelia-pal.js:20:13)
    at Container.invoke (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:559:15)
    at ProviderResolver.get (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1459:74)
    at Container.get (http://localhost:3000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:494:23)
    at Container.elementContainerGet [as get] (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1508:17)
    at HtmlBehaviorResource.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:3353:58)
    at applyInstructions (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1586:33)
    at ViewFactory.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1810:9)
    at HtmlBehaviorResource.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:3374:62)
    at applyInstructions (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1586:33)error @ aurelia-logging-console.js:62log @ aurelia-logging.js:36error @ aurelia-logging.js:69processResult @ aurelia-router.js:1616(anonymous function) @ aurelia-router.js:1569run @ es6.promise.js:107(anonymous function) @ es6.promise.js:121flush @ $.microtask.js:25
```

#### Question

What changed since yesterday to make these import statements fail?

**Comment by JeroenVinke** [comment]
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/config.js#L21

**Comment by Thanood** [comment]
And also:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/78#issuecomment-178413208

I've had this twice, reinstall fixed it twice. :smile:

**Comment by adriatic** [comment]
Please explain the meaning of providing me with the reference to config.js L21 -

**Comment by JeroenVinke** [comment]
[this block](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/config.js#L20-L24) is needed to tell SystemJS that importing 'showdown' exposes the global `showdown`, which would solve this error:

inner error: ReferenceError: showdown is not defined

**Comment by adriatic** [comment]
Well, this code **is present** in the app that crashed:

```
  meta: {
    "showdown/dist/showdown": {
      "format": "global"
    }
  },
```

What is not present is the `dist` part of  "showdown/dist/showdown" as we now use `devbuild`

Is that the problem, or am I barking at the wrong tree?

The jspm version is not locked at 0.16.15 - so maybe that is what makes the app crash?

**Comment by JeroenVinke** [comment]
Hmm, yes try locking it to 0.16.15

**Comment by adriatic** [comment]
#### This code was not present

```
  meta: {
    "showdown/dist/showdown": {
      "format": "global"
    }
  },
```

After adding the `meta` section, ensuring that I am using jspm 0.16.15 - running the "trio"

`npm install & jspm install & cd & sample & jspm install`

still did not fix this problem. So, I learned the hard way that **it is important to blow away node_modules  and jspm_packages both at the root and sample lebel**
